 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/columns", type: :request do
  # Column. As you add validations to Column, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Column.create! valid_attributes
      get columns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      column = Column.create! valid_attributes
      get column_url(column)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_column_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      column = Column.create! valid_attributes
      get edit_column_url(column)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Column" do
        expect {
          post columns_url, params: { column: valid_attributes }
        }.to change(Column, :count).by(1)
      end

      it "redirects to the created column" do
        post columns_url, params: { column: valid_attributes }
        expect(response).to redirect_to(column_url(Column.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Column" do
        expect {
          post columns_url, params: { column: invalid_attributes }
        }.to change(Column, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post columns_url, params: { column: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested column" do
        column = Column.create! valid_attributes
        patch column_url(column), params: { column: new_attributes }
        column.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the column" do
        column = Column.create! valid_attributes
        patch column_url(column), params: { column: new_attributes }
        column.reload
        expect(response).to redirect_to(column_url(column))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        column = Column.create! valid_attributes
        patch column_url(column), params: { column: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested column" do
      column = Column.create! valid_attributes
      expect {
        delete column_url(column)
      }.to change(Column, :count).by(-1)
    end

    it "redirects to the columns list" do
      column = Column.create! valid_attributes
      delete column_url(column)
      expect(response).to redirect_to(columns_url)
    end
  end
end
